---
realsense_yolo_node:
  ros__parameters:
    # ==== Pipeline & hiệu năng ====
    enable_yolo: true
    use_gpu: true
    use_fp16: true
    model_weights: "/home/azusa/azu_ws/src/my_azu/my_azu/configs/weights/yolo11n.engine"
    publish_viz: true
    show_window: false
    process_stride: 1
    imgsz: 640
    fps: 15

    # ==== Stream (đặt ở driver; để tham khảo ở đây) ====
    color_width: 640
    color_height: 480
    color_fps: 30
    depth_width: 640
    depth_height: 480
    depth_fps: 15
    align_depth_to_color: true

    # ==== Đồng bộ thời gian ====
    stamp_offset_sec: 0.0

    # ==== Vị trí gắn camera (m) ====
    cam_tx: 0.0
    cam_ty: 0.0
    cam_tz: 0.8

# Align + Sync (tránh lệch thời gian, depth khớp RGB)
    align_depth.enable: true
    enable_sync: true
    hold_back_imu_for_frames: true
    unite_imu_method: linear_interpolation
    # ==== TF ĐỘNG từ IMU ====
    use_dynamic_tf: true
    imu_topic: /camera/imu
    parent_frame: base_link
    child_frame: camera_link
    roll_offset_deg: 0.0
    pitch_offset_deg: 0.0
    yaw_offset_deg: 0.0
    tf_time_offset_sec: 0.30
