rgbd_odometry:
  ros__parameters:
    # Odom từ RGB-D + IMU của D435i (hiện KHÔNG dùng cho RTAB-Map chính,
    # nhưng vẫn giữ lại để dễ thử nghiệm nếu cần).
    frame_id: "base_link"
    odom_frame_id: "odom"
    publish_tf: true

    # Để an toàn cho map 2D, ép về 3 bậc tự do (x, y, yaw)
    Reg/Force3DoF: "true"
    subscribe_imu: false

    Vis/FeatureType: "6"           # ORB
    Vis/MaxFeatures: "1500"
    Vis/MinInliers: "8"
    FAST/Threshold: "5"
    GFTT/QualityLevel: "0.001"
    Odom/MinInliers: "8"
    Odom/ResetCountdown: "1"

    # Đồng bộ RGB + Depth (+ IMU)
    approx_sync: true
    approx_sync_max_interval: 0.15   # nới rộng cửa sổ cho 15 FPS
    topic_queue_size: 30  
    sync_queue_size: 100
    wait_for_transform: 0.5

icp_odometry:
  ros__parameters:
    # Odom chính dựa trên LiDAR (scan matching), đúng tinh thần
    # "Lidar chính xác, odom sai" trong slide bạn gửi.
    frame_id: "base_link"          # pose của robot
    odom_frame_id: "odom"
    publish_tf: true

    # Dùng dữ liệu từ scan 2D
    subscribe_scan: true

    # Làm việc trong 2D (x, y, yaw) cho map 2D ổn định
    Reg/Force3DoF: "true"

    # Tham số ICP/odometry cơ bản (có thể tinh chỉnh thêm nếu cần)
    Odom/ResetCountdown: "1"
    Odom/Strategy: "0"        # 0=ICP, 1=GICP, 2=ICP-PointToPlane (tùy phiên bản)
    Icp/VoxelSize: "0.05"
    Icp/MaxCorrespondenceDistance: "0.5"
    Icp/Iterations: "30"

rtabmap:
  ros__parameters:

    # =========================
    # TF
    # =========================
    frame_id: "base_link"
    odom_frame_id: "odom"
    map_frame_id: "map"

    subscribe_depth: true
    subscribe_scan: true
    subscribe_imu: true

    wait_for_transform: 0.5

    # =========================
    # RGB-D Sync
    # =========================
    approx_sync: true
    approx_sync_max_interval: 0.15

    topic_queue_size: 30
    sync_queue_size: 100

    # =========================
    # LOOP CLOSURE
    # =========================
    Mem/STMSize: "50"

    RGBD/ProximityBySpace: "true"
    RGBD/ProximityPathMaxNeighbors: "10"
    RGBD/ProximityMaxGraphDepth: "50"

    RGBD/NeighborLinkRefining: "true"
    RGBD/OptimizeFromGraphEnd: "true"

    Reg/Strategy: "1"

    # =========================
    # 2D MAP (LiDAR)
    # =========================
    Grid/FromDepth: "false"
    Grid/CellSize: "0.03"
    Grid/RangeMax: "6.0"
    Grid/MaxObstacleHeight: "1.2"

    # =========================
    # 3D MAP (RGB-D)
    # =========================
    Grid/3D: "true"

    Cloud/OutputVoxelized: "true"
    Cloud/OutputVoxelSize: "0.05"

    Cloud/MinDepth: "0.25"
    Cloud/MaxDepth: "4.0"

    Cloud/NoiseFiltering: "true"
    Cloud/NoiseRadius: "0.15"
    Cloud/NoiseMinNeighbors: "5"

    # =========================
    # DATABASE
    # =========================
    database_path: "~/ros2_ws/maps/my_home.db"

    database_in_memory: true
    delete_db_on_start: true
    save_db_on_shutdown: false

